using System.ComponentModel.DataAnnotations;

namespace MaintOrbit.Application.Common.Configuration;

/// <summary>Email verification token issuance settings (FR-AUTH-013).</summary>
/// <remarks>
/// The requirement fixes that verification happens and that it gates activation; it fixes no
/// numbers. These follow the shape §4.1 gives <c>invitations</c> — "hashed, single-use,
/// time-limited" — with the window chosen against what the link is for rather than copied from
/// password reset.
/// </remarks>
public sealed class EmailVerificationOptions
{
    /// <summary>Configuration section this binds to.</summary>
    public const string SectionName = "EmailVerification";

    /// <summary>
    /// Bytes of entropy in a generated token.
    /// </summary>
    /// <remarks>
    /// 09-encryption-strategy §3 hashes these with SHA-256 rather than Argon2id because they are
    /// high-entropy secrets generated by us — which only holds if they actually are. 32 bytes is
    /// 256 bits, matching every other token this system issues.
    /// </remarks>
    [Range(32, 128)]
    public int TokenBytes { get; init; } = 32;

    /// <summary>
    /// How long a verification link may be redeemed for.
    /// </summary>
    /// <remarks>
    /// <b>Twenty-four hours — longer than a password reset's hour, deliberately.</b> The two links
    /// are not equally dangerous and are not equally urgent. A reset link in the wrong hands takes
    /// over an account, so its window is as short as mail delay allows; a verification link only
    /// proves an address the holder already receives mail at, and
    /// third-party-services §7 warns that poor deliverability "breaks onboarding silently" —
    /// an hour that lapses while a message sits in a spam folder blocks an Employee from being
    /// activated at all.
    /// <para>
    /// A setting rather than a constant, so a deployment can shorten it without a code change.
    /// </para>
    /// </remarks>
    [Range(5, 10_080)]
    public int LifetimeMinutes { get; init; } = 1_440;
}
