using System.ComponentModel.DataAnnotations;

namespace MaintOrbit.Application.Common.Configuration;

/// <summary>Multi-factor authentication settings (FR-AUTH-005).</summary>
/// <remarks>
/// 02-authentication-architecture §3.6 fixes the method — "TOTP, standards-based" — and the
/// properties that matter: secrets encrypted at rest, recovery codes issued once, hashed, and
/// single-use, used codes rejected within their window. It fixes no numbers, so the defaults here
/// are RFC 6238's and RFC 4226's, and they are configuration rather than constants.
/// </remarks>
public sealed class MfaOptions
{
    /// <summary>Configuration section this binds to.</summary>
    public const string SectionName = "Mfa";

    /// <summary>
    /// The label an authenticator app shows beside the account.
    /// </summary>
    /// <remarks>
    /// Appears in the <c>otpauth://</c> URI as the issuer. Descriptive only — nothing
    /// authenticates against it, and an Employee with two accounts in one app needs it to tell
    /// them apart.
    /// </remarks>
    [Required(AllowEmptyStrings = false)]
    [StringLength(64, MinimumLength = 1)]
    public string Issuer { get; init; } = "MaintOrbit AI";

    /// <summary>
    /// Bytes of entropy in a generated TOTP secret.
    /// </summary>
    /// <remarks>
    /// 20 bytes is 160 bits, the length RFC 4226 §4 R6 recommends and the size of the HMAC-SHA1
    /// output the algorithm is defined over. The floor of 20 keeps the shared secret at least as
    /// strong as the primitive built on it.
    /// </remarks>
    [Range(20, 64)]
    public int SecretBytes { get; init; } = 20;

    /// <summary>
    /// How many recovery codes are issued at confirmation.
    /// </summary>
    /// <remarks>
    /// <b>Ten, and the number is an assumption.</b> The documentation says codes are issued once,
    /// hashed, and single-use, but never how many. Too few and a lost authenticator becomes a lost
    /// account after a couple of mistyped entries; too many and each is one more standing bypass
    /// of the second factor. Ten is the common default and it is a setting, so a deployment can
    /// choose differently without a code change.
    /// </remarks>
    [Range(4, 20)]
    public int RecoveryCodeCount { get; init; } = 10;

    /// <summary>
    /// Bytes of entropy in each recovery code.
    /// </summary>
    /// <remarks>
    /// 09-encryption-strategy §3 hashes these with SHA-256 rather than Argon2id precisely because
    /// they are "high-entropy secrets generated by us" — which only holds if they actually are.
    /// 10 bytes is 80 bits, which survives an online guessing attack by a wide margin while
    /// staying short enough that a person can copy it down without transcription errors.
    /// </remarks>
    [Range(10, 32)]
    public int RecoveryCodeBytes { get; init; } = 10;
}
