using System.ComponentModel.DataAnnotations;

namespace MaintOrbit.Application.Common.Configuration;

/// <summary>Password reset token issuance settings.</summary>
/// <remarks>
/// FR-AUTH-012 requires the token to be single-use and time-limited, and 09-encryption-strategy
/// §3.8 requires it to come from a cryptographically secure RNG. It fixes neither the length nor
/// the window, so both are configuration with defaults chosen against the documented constraints
/// rather than constants chosen here.
/// </remarks>
public sealed class PasswordResetOptions
{
    /// <summary>Configuration section this binds to.</summary>
    public const string SectionName = "PasswordReset";

    /// <summary>
    /// Bytes of entropy in a generated token.
    /// </summary>
    /// <remarks>
    /// The floor of 32 is not a style choice. 09-encryption-strategy §3 hashes these with SHA-256
    /// rather than Argon2id precisely because they are high-entropy secrets generated by us —
    /// which only holds if they actually are. 32 bytes is 256 bits, matching refresh tokens.
    /// </remarks>
    [Range(32, 128)]
    public int TokenBytes { get; init; } = 32;

    /// <summary>
    /// How long a reset token may be redeemed for.
    /// </summary>
    /// <remarks>
    /// <b>One hour, and the number is an assumption.</b> No document states a value; what is
    /// documented is the direction — the token is "time-limited" (FR-AUTH-012), it travels by
    /// email, and third-party-services §7 notes that mail can sit in a spam folder rather than
    /// arrive promptly. Too short strands the Employee mid-recovery; too long leaves a standing
    /// takeover credential in a mailbox. An hour is the shortest window that survives ordinary
    /// mail delay, and it is a setting rather than a constant so a deployment can shorten it
    /// without a code change.
    /// </remarks>
    [Range(5, 1_440)]
    public int LifetimeMinutes { get; init; } = 60;
}
