using System.ComponentModel.DataAnnotations;

namespace MaintOrbit.Application.Common.Configuration;

/// <summary>Session and refresh token lifetimes.</summary>
/// <remarks>
/// FR-AUTH-007 makes the idle window and absolute lifetime Company-configured. These are the
/// deployment-wide defaults a Company's own settings will override once the tenancy module can
/// hold them; until then they are the only values there are.
/// </remarks>
public sealed class SessionOptions
{
    /// <summary>Configuration section this binds to.</summary>
    public const string SectionName = "Sessions";

    /// <summary>
    /// How long a session may sit unused before it ends.
    /// </summary>
    /// <remarks>
    /// §3.2: ends abandoned sessions. Measured from the last genuine activity, not from the last
    /// request — a console polling in the background must not keep a session alive forever.
    /// </remarks>
    [Range(5, 43_200)]
    public int IdleTimeoutMinutes { get; init; } = 60;

    /// <summary>
    /// How long a session may live regardless of activity.
    /// </summary>
    /// <remarks>
    /// §3.2 calls this "the one that cannot be defeated by activity" — an attacker holding a live
    /// session cannot extend it indefinitely by using it.
    /// </remarks>
    [Range(15, 43_200)]
    public int AbsoluteLifetimeMinutes { get; init; } = 720;
}

/// <summary>Refresh token issuance and rotation settings.</summary>
public sealed class RefreshTokenOptions
{
    /// <summary>Configuration section this binds to.</summary>
    public const string SectionName = "RefreshTokens";

    /// <summary>
    /// Bytes of entropy in a generated token.
    /// </summary>
    /// <remarks>
    /// 09-encryption-strategy §3 hashes these with SHA-256 rather than Argon2id precisely because
    /// they are "high-entropy secrets generated by us" — which only holds if they actually are.
    /// 32 bytes is 256 bits; the floor of 32 keeps that premise true.
    /// </remarks>
    [Range(32, 128)]
    public int TokenBytes { get; init; } = 32;

    /// <summary>
    /// How long a refresh token may be exchanged for.
    /// </summary>
    /// <remarks>
    /// Bounded independently of the session so a token cannot outlive its usefulness. The session's
    /// absolute expiry still ends the chain regardless.
    /// </remarks>
    [Range(1, 43_200)]
    public int LifetimeMinutes { get; init; } = 720;

    /// <summary>
    /// A window in which re-presenting the immediately-previous token is tolerated.
    /// </summary>
    /// <remarks>
    /// <b>Defaults to zero — disabled — deliberately.</b> 02-authentication-architecture §3.3
    /// describes the problem it solves (two tabs refreshing at once, or a retry after a dropped
    /// response, can trigger a false family revocation) and then says the window's length "is a
    /// tuning decision that must be measured rather than guessed". Picking a number here would be
    /// guessing, and a grace window is a deliberate weakening of reuse detection: for its duration,
    /// a stolen token is accepted alongside the legitimate one.
    /// </remarks>
    [Range(0, 60)]
    public int ReuseGraceSeconds { get; init; }
}
