using MaintOrbit.Domain.Modules.Identity.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MaintOrbit.Infrastructure.Persistence.Configurations.Identity;

/// <summary>
/// Maps <see cref="Employee"/> to <c>identity.employees</c>.
/// </summary>
/// <remarks>
/// Table and column names are written in PascalCase and converted by
/// <c>NamingConventions.ApplySnakeCaseNames</c>, which runs after every configuration. Writing
/// the final names here would work and would leave the convention untested by the one entity
/// that exists.
/// <para>
/// Mapping only — no defaults that encode a rule, no value generation that decides a lifecycle.
/// Anything the aggregate is responsible for stays in the aggregate, where it can be tested
/// without a database.
/// </para>
/// </remarks>
internal sealed class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
{
    public void Configure(EntityTypeBuilder<Employee> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.ToTable(
            "Employees",
            Schemas.Identity,
            table => table.HasCheckConstraint(
                "ck_employees_status",
                "status IN ('Invited', 'Active', 'Suspended', 'Removed')"));

        builder.HasKey(employee => employee.Id);

        builder.Property(employee => employee.Id)
            // Generated by the application as UUIDv7. TD-5 decides whether PostgreSQL 18's native
            // generator becomes available; until then the database must not supply a value, and
            // afterwards this stays correct.
            .ValueGeneratedNever();

        builder.Property(employee => employee.CompanyId).IsRequired();

        builder.Property(employee => employee.Email).IsRequired();

        builder.Property(employee => employee.EmailVerifiedAtUtc);

        builder.Property(employee => employee.Status)
            // Stored as text. An ordinal would be two bytes smaller and would make every row
            // unreadable without this file, and would silently change meaning if a member were
            // ever inserted into the middle of the enum.
            .HasConversion<string>()
            .HasMaxLength(32)
            .IsRequired();

        builder.Property(employee => employee.PrimaryTeamId);

        builder.Property(employee => employee.DeletedAtUtc);
        builder.Property(employee => employee.DeletedByEmployeeId);

        builder.Property(employee => employee.PseudonymizedAtUtc);

        builder.Property(employee => employee.CreatedAtUtc).IsRequired();
        builder.Property(employee => employee.CreatedByEmployeeId);

        builder.Property(employee => employee.UpdatedAtUtc).IsRequired();
        builder.Property(employee => employee.UpdatedByEmployeeId);

        builder.Property(employee => employee.RowVersion)
            .IsConcurrencyToken()
            .IsRequired();

        builder.Ignore(employee => employee.IsDeleted);

        // Unique per Company, and partial so the index stops applying once a row is soft-deleted.
        // §1.8 and §9 both call this out: without the filter, removing an Employee would
        // permanently reserve their address against their own Company.
        builder.HasIndex(employee => new { employee.CompanyId, employee.Email })
            .IsUnique()
            .HasFilter("deleted_at_utc IS NULL");

        builder.HasIndex(employee => new { employee.CompanyId, employee.Status });
    }
}
