<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MaintOrbit.Application\MaintOrbit.Application.csproj" />
    <ProjectReference Include="..\MaintOrbit.Domain\MaintOrbit.Domain.csproj" />
    <ProjectReference Include="..\MaintOrbit.Shared\MaintOrbit.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
