using System.Net;
using MaintOrbit.Shared.Constants;
using MaintOrbit.Shared.Primitives;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.Hosting;

namespace MaintOrbit.Api.FunctionalTests.Middleware;

/// <summary>
/// Covers correlation at the HTTP boundary.
/// </summary>
/// <remarks>
/// NFR-OBS-002 requires the identifier to be returned to the caller on every request. These
/// tests assert it across success, failure, and a path that was never mapped — the last one
/// matters because a 404 is generated by the framework rather than by any code of ours.
/// </remarks>
public sealed class CorrelationIdMiddlewareTests
{
    [Fact]
    public async Task CorrelationId_IsReturned_WhenTheCallerSuppliesNone()
    {
        using var host = PipelineTestHost.Build();
        await host.StartAsync();
        using var client = host.GetTestClient();

        using var response = await client.GetAsync(new Uri(PipelineTestHost.SucceedingPath, UriKind.Relative));

        var returned = Assert.Single(response.Headers.GetValues(CorrelationHeaderNames.CorrelationId));
        Assert.True(CorrelationId.IsWellFormed(returned));
    }

    [Fact]
    public async Task CorrelationId_IsPreserved_WhenTheCallerSuppliesAValidOne()
    {
        const string Supplied = "customer-trace-42";

        using var host = PipelineTestHost.Build();
        await host.StartAsync();
        using var client = host.GetTestClient();
        client.DefaultRequestHeaders.Add(CorrelationHeaderNames.CorrelationId, Supplied);

        using var response = await client.GetAsync(new Uri(PipelineTestHost.SucceedingPath, UriKind.Relative));

        Assert.Equal(Supplied, Assert.Single(
            response.Headers.GetValues(CorrelationHeaderNames.CorrelationId)));
    }

    [Fact]
    public async Task CorrelationId_IsReplaced_WhenTheCallerSuppliesAMalformedOne()
    {
        // Header values reach us already stripped of line breaks by the HTTP stack, so the
        // realistic hostile input at this layer is an over-long value. Either way the contract
        // is the same: what comes back is always well-formed.
        var oversized = new string('x', CorrelationId.MaxLength + 1);

        using var host = PipelineTestHost.Build();
        await host.StartAsync();
        using var client = host.GetTestClient();
        client.DefaultRequestHeaders.Add(CorrelationHeaderNames.CorrelationId, oversized);

        using var response = await client.GetAsync(new Uri(PipelineTestHost.SucceedingPath, UriKind.Relative));

        var returned = Assert.Single(response.Headers.GetValues(CorrelationHeaderNames.CorrelationId));
        Assert.NotEqual(oversized, returned);
        Assert.True(CorrelationId.IsWellFormed(returned));
    }

    [Fact]
    public async Task CorrelationId_IsReturned_OnAnUnhandledException()
    {
        // The response a caller is most likely to quote back to support.
        using var host = PipelineTestHost.Build();
        await host.StartAsync();
        using var client = host.GetTestClient();

        using var response = await client.GetAsync(new Uri(PipelineTestHost.ThrowingPath, UriKind.Relative));

        Assert.Equal(HttpStatusCode.InternalServerError, response.StatusCode);
        Assert.True(CorrelationId.IsWellFormed(
            Assert.Single(response.Headers.GetValues(CorrelationHeaderNames.CorrelationId))));
    }

    [Fact]
    public async Task CorrelationId_IsReturned_OnAResponseNoMiddlewareOfOursProduced()
    {
        // A 404 comes from routing, not from application code. Setting the header through an
        // OnStarting callback rather than at the end of the pipeline is what makes it appear
        // here too.
        using var host = PipelineTestHost.Build();
        await host.StartAsync();
        using var client = host.GetTestClient();

        using var response = await client.GetAsync(new Uri("/nothing-is-mapped-here", UriKind.Relative));

        Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
        Assert.True(response.Headers.Contains(CorrelationHeaderNames.CorrelationId));
    }

    [Fact]
    public async Task EachRequest_ReceivesItsOwnIdentifier()
    {
        using var host = PipelineTestHost.Build();
        await host.StartAsync();
        using var client = host.GetTestClient();

        using var first = await client.GetAsync(new Uri(PipelineTestHost.SucceedingPath, UriKind.Relative));
        using var second = await client.GetAsync(new Uri(PipelineTestHost.SucceedingPath, UriKind.Relative));

        Assert.NotEqual(
            Assert.Single(first.Headers.GetValues(CorrelationHeaderNames.CorrelationId)),
            Assert.Single(second.Headers.GetValues(CorrelationHeaderNames.CorrelationId)));
    }
}
