<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaintOrbit.Domain\MaintOrbit.Domain.csproj" />
    <ProjectReference Include="..\MaintOrbit.Shared\MaintOrbit.Shared.csproj" />
  </ItemGroup>


</Project>
