using System.Security.Cryptography;
using System.Text;
using MaintOrbit.Application.Abstractions.Security;
using MaintOrbit.Application.Common.Configuration;
using MaintOrbit.Domain.Modules.Identity.ValueObjects;
using Microsoft.Extensions.Options;

namespace MaintOrbit.Infrastructure.Authentication;

/// <summary>
/// Generates refresh tokens and hashes presented ones with SHA-256.
/// </summary>
/// <remarks>
/// SHA-256 rather than Argon2id, per 09-encryption-strategy §3's decision tree: the secret is
/// high-entropy and generated by us, so brute force is infeasible regardless and a slow hash would
/// add cost without adding security. The same reasoning that makes Argon2id right for passwords
/// makes it wrong here.
/// <para>
/// The digest is unsalted, which is correct for this input and would not be for a password: a salt
/// defends against precomputation across a corpus of guessable values, and there is no corpus of
/// 256-bit random tokens to precompute. It is also what allows lookup by hash — a per-row salt
/// would make finding a presented token a table scan.
/// </para>
/// </remarks>
internal sealed class RefreshTokenFactory(IOptions<RefreshTokenOptions> options) : IRefreshTokenFactory
{
    /// <inheritdoc />
    public IssuedRefreshToken Issue()
    {
        var bytes = RandomNumberGenerator.GetBytes(options.Value.TokenBytes);

        try
        {
            // URL-safe, so the token survives a cookie, a header, and a query string without
            // re-encoding — and without a re-encoding bug turning two distinct tokens into one.
            var token = Base64UrlEncode(bytes);

            return new IssuedRefreshToken(token, Hash(token));
        }
        finally
        {
            CryptographicOperations.ZeroMemory(bytes);
        }
    }

    /// <inheritdoc />
    public RefreshTokenHash Hash(string presentedToken)
    {
        ArgumentException.ThrowIfNullOrEmpty(presentedToken);

        var digest = SHA256.HashData(Encoding.UTF8.GetBytes(presentedToken));

        return RefreshTokenHash.Create(Convert.ToHexStringLower(digest));
    }

    private static string Base64UrlEncode(ReadOnlySpan<byte> bytes) =>
        Convert.ToBase64String(bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_');
}
