// <auto-generated />
using System;
using MaintOrbit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaintOrbit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MaintOrbitDbContext))]
    [Migration("20260803100029_Authorization")]
    partial class Authorization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_employee_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_employee_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at_utc");

                    b.Property<Guid?>("PrimaryTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_team_id");

                    b.Property<DateTimeOffset?>("PseudonymizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pseudonymized_at_utc");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_employee_id");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("CompanyId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_company_id_email")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("CompanyId", "Status")
                        .HasDatabaseName("ix_employees_company_id_status");

                    b.ToTable("employees", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_employees_status", "status IN ('Invited', 'Active', 'Suspended', 'Removed')");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.EmployeeCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("algorithm");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_employee_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("HashParameters")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hash_parameters");

                    b.Property<DateTimeOffset?>("LockoutUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_until_utc");

                    b.Property<DateTimeOffset>("PasswordChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PasswordVersion")
                        .HasColumnType("integer")
                        .HasColumnName("password_version");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("boolean")
                        .HasColumnName("require_password_change");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_employee_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_credentials");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_credentials_employee_id");

                    b.ToTable("employee_credentials", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_employee_credentials_algorithm", "algorithm IN ('Argon2id')");

                            t.HasCheckConstraint("ck_employee_credentials_failed_login_count", "failed_login_count >= 0");

                            t.HasCheckConstraint("ck_employee_credentials_password_version", "password_version >= 1");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.EmployeeRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_employee_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_code");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope_type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_employee_roles");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_employee_roles_company_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_roles_employee_id");

                    b.HasIndex("RoleCode")
                        .HasDatabaseName("ix_employee_roles_role_code");

                    b.HasIndex("EmployeeId", "RoleCode", "ScopeType", "ScopeId")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_roles_employee_id_role_code_scope");

                    b.ToTable("employee_roles", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_employee_roles_scope_target", "(scope_type = 'Team') = (scope_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_employee_roles_scope_type", "scope_type IN ('Company', 'Team', 'Self')");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "identity");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_refresh_tokens_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_expiry", "expires_at_utc > issued_at_utc");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.RoleDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_built_in");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_role_definitions");

                    b.ToTable("role_definitions", "identity");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.RolePermission", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_code");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission_code");

                    b.HasKey("RoleCode", "PermissionCode")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionCode")
                        .HasDatabaseName("ix_role_permissions_permission_code");

                    b.HasIndex("RoleCode")
                        .HasDatabaseName("ix_role_permissions_role_code");

                    b.ToTable("role_permissions", "identity");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at_utc");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_type");

                    b.Property<string>("CoarseLocation")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("coarse_location");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_label");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastActiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at_utc");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_sessions_company_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_sessions_employee_id_active")
                        .HasFilter("revoked_at_utc IS NULL");

                    b.ToTable("sessions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_sessions_absolute_expiry", "absolute_expires_at_utc > created_at_utc");

                            t.HasCheckConstraint("ck_sessions_client_type", "client_type IN ('Unknown', 'WebConsole', 'VsCodeExtension', 'ServerApplication')");

                            t.HasCheckConstraint("ck_sessions_revocation", "(revoked_at_utc IS NULL) = (revocation_reason IS NULL)");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.EmployeeCredential", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("MaintOrbit.Domain.Modules.Identity.Entities.EmployeeCredential", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_credentials_employees_employee_id");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.EmployeeRole", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_roles_employees_employee_id");

                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.RoleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_roles_role_definitions_role_code");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_sessions_session_id");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.RolePermission", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.RoleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_role_definitions_role_code");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.Session", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_employees_employee_id");
                });
#pragma warning restore 612, 618
        }
    }
}
