// <auto-generated />
using System;
using MaintOrbit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaintOrbit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MaintOrbitDbContext))]
    [Migration("20260731080309_EmployeeCredentials")]
    partial class EmployeeCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_employee_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_employee_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at_utc");

                    b.Property<Guid?>("PrimaryTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_team_id");

                    b.Property<DateTimeOffset?>("PseudonymizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pseudonymized_at_utc");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_employee_id");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("CompanyId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_company_id_email")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("CompanyId", "Status")
                        .HasDatabaseName("ix_employees_company_id_status");

                    b.ToTable("employees", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_employees_status", "status IN ('Invited', 'Active', 'Suspended', 'Removed')");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.EmployeeCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("algorithm");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_employee_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("HashParameters")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hash_parameters");

                    b.Property<DateTimeOffset?>("LockoutUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_until_utc");

                    b.Property<DateTimeOffset>("PasswordChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PasswordVersion")
                        .HasColumnType("integer")
                        .HasColumnName("password_version");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("boolean")
                        .HasColumnName("require_password_change");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_employee_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_credentials");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_credentials_employee_id");

                    b.ToTable("employee_credentials", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_employee_credentials_algorithm", "algorithm IN ('Argon2id')");

                            t.HasCheckConstraint("ck_employee_credentials_failed_login_count", "failed_login_count >= 0");

                            t.HasCheckConstraint("ck_employee_credentials_password_version", "password_version >= 1");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.EmployeeCredential", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("MaintOrbit.Domain.Modules.Identity.Entities.EmployeeCredential", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_credentials_employees_employee_id");
                });
#pragma warning restore 612, 618
        }
    }
}
