// <auto-generated />
using System;
using MaintOrbit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaintOrbit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MaintOrbitDbContext))]
    [Migration("20260808100833_AuditEvents")]
    partial class AuditEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Auditing.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_employee_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Context")
                        .HasColumnType("jsonb")
                        .HasColumnName("context");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<string>("StreamEntryId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stream_entry_id");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.HasKey("Id", "OccurredAtUtc")
                        .HasName("pk_audit_events");

                    b.HasIndex("CompanyId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_company_id_occurred_at_utc");

                    b.HasIndex("StreamEntryId", "OccurredAtUtc")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_events_stream_entry_id");

                    b.HasIndex("CompanyId", "Action", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_company_id_action_occurred_at_utc");

                    b.HasIndex("CompanyId", "ActorEmployeeId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_company_id_actor_employee_id_occurred_at_utc");

                    b.ToTable("audit_events", "auditing");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.CompanyAuthenticationPolicy", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<int>("AbsoluteLifetimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("absolute_lifetime_minutes");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("IdleTimeoutMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("idle_timeout_minutes");

                    b.Property<int>("LockoutMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("lockout_minutes");

                    b.Property<int>("MaximumFailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_failed_attempts");

                    b.Property<bool>("MfaRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_required");

                    b.Property<int>("MinimumPasswordLength")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_password_length");

                    b.Property<bool>("RequireBreachCheck")
                        .HasColumnType("boolean")
                        .HasColumnName("require_breach_check");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_employee_id");

                    b.HasKey("CompanyId")
                        .HasName("pk_company_authentication_policies");

                    b.ToTable("company_authentication_policies", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_company_authentication_policies_absolute_lifetime", "absolute_lifetime_minutes BETWEEN 15 AND 43200");

                            t.HasCheckConstraint("ck_company_authentication_policies_failed_attempts", "maximum_failed_attempts BETWEEN 3 AND 20");

                            t.HasCheckConstraint("ck_company_authentication_policies_idle_timeout", "idle_timeout_minutes BETWEEN 5 AND 43200");

                            t.HasCheckConstraint("ck_company_authentication_policies_lifetime_order", "absolute_lifetime_minutes >= idle_timeout_minutes");

                            t.HasCheckConstraint("ck_company_authentication_policies_lockout_minutes", "lockout_minutes BETWEEN 1 AND 1440");

                            t.HasCheckConstraint("ck_company_authentication_policies_password_length", "minimum_password_length BETWEEN 12 AND 128");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset?>("InvalidatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at_utc");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_email_verification_tokens");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_email_verification_tokens_employee_id_outstanding")
                        .HasFilter("consumed_at_utc IS NULL AND invalidated_at_utc IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_email_verification_tokens_token_hash");

                    b.ToTable("email_verification_tokens", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_email_verification_tokens_expiry", "expires_at_utc > issued_at_utc");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_employee_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_employee_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at_utc");

                    b.Property<Guid?>("PrimaryTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_team_id");

                    b.Property<DateTimeOffset?>("PseudonymizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pseudonymized_at_utc");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_employee_id");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("CompanyId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_company_id_email")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("CompanyId", "Status")
                        .HasDatabaseName("ix_employees_company_id_status");

                    b.ToTable("employees", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_employees_status", "status IN ('Invited', 'Active', 'Suspended', 'Removed')");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.EmployeeCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("algorithm");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_employee_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("HashParameters")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hash_parameters");

                    b.Property<DateTimeOffset?>("LockoutUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_until_utc");

                    b.Property<DateTimeOffset>("PasswordChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PasswordVersion")
                        .HasColumnType("integer")
                        .HasColumnName("password_version");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("boolean")
                        .HasColumnName("require_password_change");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_employee_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_credentials");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_credentials_employee_id");

                    b.ToTable("employee_credentials", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_employee_credentials_algorithm", "algorithm IN ('Argon2id')");

                            t.HasCheckConstraint("ck_employee_credentials_failed_login_count", "failed_login_count >= 0");

                            t.HasCheckConstraint("ck_employee_credentials_password_version", "password_version >= 1");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.EmployeeRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_employee_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_code");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope_type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_employee_roles");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_employee_roles_company_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_employee_roles_employee_id");

                    b.HasIndex("RoleCode")
                        .HasDatabaseName("ix_employee_roles_role_code");

                    b.HasIndex("EmployeeId", "RoleCode", "ScopeType", "ScopeId")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_roles_employee_id_role_code_scope");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("EmployeeId", "RoleCode", "ScopeType", "ScopeId"), false);

                    b.ToTable("employee_roles", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_employee_roles_scope_target", "(scope_type = 'Team') = (scope_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_employee_roles_scope_type", "scope_type IN ('Company', 'Team', 'Self')");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.MfaEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<long?>("LastAcceptedTimeStep")
                        .HasColumnType("bigint")
                        .HasColumnName("last_accepted_time_step");

                    b.Property<DateTimeOffset?>("LastVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at_utc");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("method");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_mfa_enrollments");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_mfa_enrollments_employee_id_active")
                        .HasFilter("disabled_at_utc IS NULL");

                    b.ToTable("mfa_enrollments", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_mfa_enrollments_confirmation", "(status = 'Pending') = (confirmed_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_mfa_enrollments_status", "status IN ('Pending', 'Confirmed', 'Disabled')");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.MfaRecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_mfa_recovery_codes");

                    b.HasIndex("EnrollmentId", "CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ux_mfa_recovery_codes_enrollment_id_code_hash");

                    b.ToTable("mfa_recovery_codes", "identity");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset?>("InvalidatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at_utc");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<string>("RequestedFromIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("requested_from_ip_address");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_password_reset_tokens_employee_id_outstanding")
                        .HasFilter("consumed_at_utc IS NULL AND invalidated_at_utc IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_password_reset_tokens_token_hash");

                    b.ToTable("password_reset_tokens", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_password_reset_tokens_expiry", "expires_at_utc > requested_at_utc");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "identity");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_refresh_tokens_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_expiry", "expires_at_utc > issued_at_utc");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.RoleDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_built_in");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_role_definitions");

                    b.ToTable("role_definitions", "identity");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.RolePermission", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_code");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission_code");

                    b.HasKey("RoleCode", "PermissionCode")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionCode")
                        .HasDatabaseName("ix_role_permissions_permission_code");

                    b.HasIndex("RoleCode")
                        .HasDatabaseName("ix_role_permissions_role_code");

                    b.ToTable("role_permissions", "identity");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at_utc");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_type");

                    b.Property<string>("CoarseLocation")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("coarse_location");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_label");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastActiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at_utc");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_sessions_company_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_sessions_employee_id_active")
                        .HasFilter("revoked_at_utc IS NULL");

                    b.ToTable("sessions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_sessions_absolute_expiry", "absolute_expires_at_utc > created_at_utc");

                            t.HasCheckConstraint("ck_sessions_client_type", "client_type IN ('Unknown', 'WebConsole', 'VsCodeExtension', 'ServerApplication')");

                            t.HasCheckConstraint("ck_sessions_revocation", "(revoked_at_utc IS NULL) = (revocation_reason IS NULL)");
                        });
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_verification_tokens_employees_employee_id");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.EmployeeCredential", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("MaintOrbit.Domain.Modules.Identity.Entities.EmployeeCredential", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_credentials_employees_employee_id");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.EmployeeRole", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_roles_employees_employee_id");

                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.RoleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employee_roles_role_definitions_role_code");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.MfaEnrollment", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mfa_enrollments_employees_employee_id");

                    b.OwnsOne("MaintOrbit.Domain.Modules.Identity.ValueObjects.SecretEnvelope", "Secret", b1 =>
                        {
                            b1.Property<Guid>("MfaEnrollmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AlgorithmId")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("algorithm_id");

                            b1.Property<byte[]>("AuthenticationTag")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("bytea")
                                .HasColumnName("secret_auth_tag");

                            b1.Property<byte[]>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("secret_ciphertext");

                            b1.Property<int>("DekVersion")
                                .HasColumnType("integer")
                                .HasColumnName("dek_version");

                            b1.Property<byte[]>("Nonce")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("bytea")
                                .HasColumnName("secret_iv");

                            b1.HasKey("MfaEnrollmentId")
                                .HasName("pk_mfa_enrollments");

                            b1.ToTable("mfa_enrollments", "identity");

                            b1.WithOwner()
                                .HasForeignKey("MfaEnrollmentId")
                                .HasConstraintName("fk_mfa_enrollments_mfa_enrollments_id");
                        });

                    b.Navigation("Secret")
                        .IsRequired();
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.MfaRecoveryCode", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.MfaEnrollment", null)
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mfa_recovery_codes_mfa_enrollments_enrollment_id");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_employees_employee_id");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.RefreshToken", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_sessions_session_id");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.RolePermission", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.RoleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_role_definitions_role_code");
                });

            modelBuilder.Entity("MaintOrbit.Domain.Modules.Identity.Entities.Session", b =>
                {
                    b.HasOne("MaintOrbit.Domain.Modules.Identity.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_employees_employee_id");
                });
#pragma warning restore 612, 618
        }
    }
}
