<Project Sdk="Microsoft.NET.Sdk">


  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MaintOrbit.Domain\MaintOrbit.Domain.csproj" />
    <ProjectReference Include="..\..\src\MaintOrbit.Application\MaintOrbit.Application.csproj" />
    <ProjectReference Include="..\..\src\MaintOrbit.Infrastructure\MaintOrbit.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\MaintOrbit.Api\MaintOrbit.Api.csproj" />
    <ProjectReference Include="..\..\src\MaintOrbit.Shared\MaintOrbit.Shared.csproj" />
  </ItemGroup>

</Project>