using MaintOrbit.Domain.Modules.Identity.ValueObjects;

namespace MaintOrbit.Application.Abstractions.Security;

/// <summary>
/// Generates recovery codes and hashes presented ones.
/// </summary>
/// <remarks>
/// A port so the application layer can issue and look up codes without knowing the entropy source,
/// the encoding, or the digest. That the hash is SHA-256 is a decision 09-encryption-strategy §3
/// makes on entropy grounds, and it belongs behind this seam rather than at every call site.
/// </remarks>
public interface IRecoveryCodeFactory
{
    /// <summary>
    /// Generates a full set of codes.
    /// </summary>
    /// <remarks>
    /// The plaintext codes are returned exactly once, for display to the Employee.
    /// 02-authentication-architecture §3.6 issues them once; nothing stores them, so a set that is
    /// lost is regenerated by re-enrolling rather than recovered.
    /// </remarks>
    IReadOnlyList<IssuedRecoveryCode> IssueSet();

    /// <summary>Hashes a code presented by an Employee, so it can be looked up.</summary>
    RecoveryCodeHash Hash(string presentedCode);
}

/// <summary>A freshly generated recovery code and the hash that will be stored for it.</summary>
public sealed record IssuedRecoveryCode(string Code, RecoveryCodeHash Hash)
{
    /// <inheritdoc />
    public override string ToString() => "[REDACTED]";

    [System.Diagnostics.CodeAnalysis.SuppressMessage(
        "Performance",
        "CA1822:Mark members as static",
        Justification = "PrintMembers is the record-generated member the compiler calls on an " +
                        "instance; a static one would not be used and the code would print.")]
    private bool PrintMembers(System.Text.StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.Append("[REDACTED]");
        return true;
    }
}
