using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace MaintOrbit.Domain.Modules.Identity.ValueObjects;

/// <summary>
/// The stored hash of an email verification token — C4 data.
/// </summary>
/// <remarks>
/// The same treatment §4.1 gives <c>invitations.token_hash</c>, which it describes as "hashed,
/// single-use, time-limited". Storing the token itself would make the database a source of live
/// credentials for proving control of an address — and FR-AUTH-013 makes that proof the gate on an
/// account becoming active.
/// <para>
/// <b>SHA-256, not Argon2id</b>, per 09-encryption-strategy §3's decision tree: a high-entropy
/// secret generated by us is hashed with SHA-256 because brute force is infeasible regardless, and
/// a slow hash would add cost without adding security.
/// </para>
/// <para>
/// Like the other C4 digests here, it refuses to print itself.
/// </para>
/// </remarks>
[DebuggerDisplay("EmailVerificationTokenHash [REDACTED]")]
public sealed record EmailVerificationTokenHash
{
    /// <summary>Length of a SHA-256 digest in lowercase hexadecimal.</summary>
    public const int Length = 64;

    private EmailVerificationTokenHash(string value) => Value = value;

    /// <summary>The hexadecimal digest.</summary>
    public string Value { get; }

    /// <summary>
    /// Creates a hash from a digest already computed.
    /// </summary>
    /// <remarks>
    /// Shape is fixed rather than merely bounded: SHA-256 always produces 32 bytes, so anything of
    /// another length did not come from the hasher and a lookup against it would silently match
    /// nothing — which reads as "no such token" rather than as the defect it is.
    /// </remarks>
    public static bool TryCreate(
        string? candidate, [NotNullWhen(true)] out EmailVerificationTokenHash? hash)
    {
        hash = null;

        if (candidate is null || candidate.Length != Length)
        {
            return false;
        }

        foreach (var character in candidate)
        {
            var isLowerHex = char.IsAsciiDigit(character) || character is >= 'a' and <= 'f';

            if (!isLowerHex)
            {
                return false;
            }
        }

        hash = new EmailVerificationTokenHash(candidate);
        return true;
    }

    /// <summary>Creates a hash from a digest already known to be well formed.</summary>
    /// <exception cref="ArgumentException">The value is not a lowercase SHA-256 digest.</exception>
    public static EmailVerificationTokenHash Create(string candidate)
    {
        if (!TryCreate(candidate, out var hash))
        {
            // Never echoed: this is the lookup key for a credential that proves control of an address.
            throw new ArgumentException(
                "Value is not a lowercase hexadecimal SHA-256 digest.", nameof(candidate));
        }

        return hash;
    }

    /// <inheritdoc />
    public override string ToString() => "[REDACTED]";

    [SuppressMessage(
        "Performance",
        "CA1822:Mark members as static",
        Justification = "PrintMembers is the record-generated member the compiler calls on an " +
                        "instance; a static one would not be used and the digest would print.")]
    private bool PrintMembers(System.Text.StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.Append("[REDACTED]");
        return true;
    }
}
