using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace MaintOrbit.Domain.Modules.Identity.ValueObjects;

/// <summary>
/// The stored hash of a password reset token — C4 data.
/// </summary>
/// <remarks>
/// 09-encryption-strategy §3.8 requires password reset tokens to come from a cryptographically
/// secure RNG and to be single-use and time-limited. Storing the token itself would make the
/// database a source of live account-recovery credentials, so only the digest is kept — the same
/// treatment <c>invitations.token_hash</c> gets in §4.1, which §4.1 describes as "hashed,
/// single-use, time-limited".
/// <para>
/// <b>SHA-256, not Argon2id.</b> §3's decision tree turns on entropy, not on what the secret is
/// for: a high-entropy secret generated by us is hashed with SHA-256 because brute force is
/// infeasible regardless, and a slow hash would add cost without adding security. Argon2id is for
/// the low-entropy secret a human chose — the password this token is used to replace.
/// </para>
/// <para>
/// Like <see cref="PasswordHash"/> and <see cref="RefreshTokenHash"/>, it refuses to print itself.
/// This is the lookup key for a credential that can take over an account.
/// </para>
/// </remarks>
[DebuggerDisplay("PasswordResetTokenHash [REDACTED]")]
public sealed record PasswordResetTokenHash
{
    /// <summary>Length of a SHA-256 digest in lowercase hexadecimal.</summary>
    public const int Length = 64;

    private PasswordResetTokenHash(string value) => Value = value;

    /// <summary>The hexadecimal digest.</summary>
    public string Value { get; }

    /// <summary>
    /// Creates a hash from a digest already computed.
    /// </summary>
    /// <remarks>
    /// Shape is fixed rather than merely bounded: SHA-256 always produces 32 bytes, so anything of
    /// another length did not come from the hasher and a lookup against it would silently match
    /// nothing — which reads as "no such token" rather than as the defect it is.
    /// </remarks>
    public static bool TryCreate(
        string? candidate, [NotNullWhen(true)] out PasswordResetTokenHash? hash)
    {
        hash = null;

        if (candidate is null || candidate.Length != Length)
        {
            return false;
        }

        foreach (var character in candidate)
        {
            var isLowerHex = char.IsAsciiDigit(character) || character is >= 'a' and <= 'f';

            if (!isLowerHex)
            {
                return false;
            }
        }

        hash = new PasswordResetTokenHash(candidate);
        return true;
    }

    /// <summary>Creates a hash from a digest already known to be well formed.</summary>
    /// <exception cref="ArgumentException">The value is not a lowercase SHA-256 digest.</exception>
    public static PasswordResetTokenHash Create(string candidate)
    {
        if (!TryCreate(candidate, out var hash))
        {
            // Never echoed: this is the lookup key for an account-recovery credential.
            throw new ArgumentException(
                "Value is not a lowercase hexadecimal SHA-256 digest.", nameof(candidate));
        }

        return hash;
    }

    /// <inheritdoc />
    public override string ToString() => "[REDACTED]";

    [SuppressMessage(
        "Performance",
        "CA1822:Mark members as static",
        Justification = "PrintMembers is the record-generated member the compiler calls on an " +
                        "instance; a static one would not be used and the digest would print.")]
    private bool PrintMembers(System.Text.StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.Append("[REDACTED]");
        return true;
    }
}
