using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace MaintOrbit.Domain.Modules.Identity.ValueObjects;

/// <summary>
/// The stored hash of a refresh token — C4 data.
/// </summary>
/// <remarks>
/// SD-014 stores refresh tokens "hashed server-side; never recoverable", so that a database
/// compromise does not yield usable tokens. This type holds only the hash; the token itself exists
/// exactly once, on its way to the client, and is never persisted.
/// <para>
/// <b>SHA-256, not Argon2id</b>, and 09-encryption-strategy §3 gives the rule as a decision tree:
/// a high-entropy secret generated by us is hashed with SHA-256, because brute force against it is
/// infeasible regardless and a slow hash would only add cost. Argon2id is for low-entropy secrets
/// a human chose.
/// </para>
/// <para>
/// Like <c>PasswordHash</c>, it refuses to print itself. A refresh token hash is the lookup key
/// for a bearer credential, and <c>refresh_tokens</c> is C4.
/// </para>
/// </remarks>
[DebuggerDisplay("RefreshTokenHash [REDACTED]")]
public sealed record RefreshTokenHash
{
    /// <summary>Length of a SHA-256 digest in lowercase hexadecimal.</summary>
    public const int Length = 64;

    private RefreshTokenHash(string value) => Value = value;

    /// <summary>The hexadecimal digest.</summary>
    public string Value { get; }

    /// <summary>
    /// Creates a hash from a digest already computed.
    /// </summary>
    /// <remarks>
    /// Shape is fixed rather than merely bounded: SHA-256 always produces 32 bytes, so anything of
    /// another length did not come from the hasher, and a lookup against it would silently match
    /// nothing.
    /// </remarks>
    public static bool TryCreate(string? candidate, [NotNullWhen(true)] out RefreshTokenHash? hash)
    {
        hash = null;

        if (candidate is null || candidate.Length != Length)
        {
            return false;
        }

        foreach (var character in candidate)
        {
            var isLowerHex = char.IsAsciiDigit(character) || character is >= 'a' and <= 'f';

            if (!isLowerHex)
            {
                return false;
            }
        }

        hash = new RefreshTokenHash(candidate);
        return true;
    }

    /// <summary>Creates a hash from a digest already known to be well formed.</summary>
    /// <exception cref="ArgumentException">The value is not a lowercase SHA-256 digest.</exception>
    public static RefreshTokenHash Create(string candidate)
    {
        if (!TryCreate(candidate, out var hash))
        {
            // Never echoed: this is the lookup key for a bearer credential.
            throw new ArgumentException(
                "Value is not a lowercase hexadecimal SHA-256 digest.", nameof(candidate));
        }

        return hash;
    }

    /// <inheritdoc />
    public override string ToString() => "[REDACTED]";

    [SuppressMessage(
        "Performance",
        "CA1822:Mark members as static",
        Justification = "PrintMembers is the record-generated member the compiler calls on an " +
                        "instance; a static one would not be used and the digest would print.")]
    private bool PrintMembers(System.Text.StringBuilder builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.Append("[REDACTED]");
        return true;
    }
}
