<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MaintOrbit.Application\MaintOrbit.Application.csproj" />
    <ProjectReference Include="..\MaintOrbit.Infrastructure\MaintOrbit.Infrastructure.csproj" />
    <ProjectReference Include="..\MaintOrbit.Shared\MaintOrbit.Shared.csproj" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>

</Project>
